from typing import Dict, Any

def generate_report(case_id: str, parsed_data: Dict[str, Any], adc_confirmed: bool) -> str:
    """
    Generates a formatted text report from structured findings.
    """
    
    findings_list = []
    
    # Construct Findings Section
    if parsed_data["infarction_present"]:
        side = parsed_data["laterality"]
        loc = ", ".join(parsed_data["location"])
        stage = parsed_data["stage"]
        terr = parsed_data["vascular_territory"]
        
        findings_list.append(f"• DIFFUSION: Abnormal high signal on DWI in the {side.lower()} {loc.lower()}.")
        
        if adc_confirmed:
            findings_list.append("• ADC: Corresponding hypointensity confirms restricted diffusion.")
        else:
            findings_list.append("• ADC: No definite corresponding hypointensity (T2 shine-through cannot be excluded).")
            
        findings_list.append(f"• STAGE: Findings are consistent with {stage.lower()} evolution.")
        if terr != "Indeterminate":
             findings_list.append(f"• TERRITORY: Suggestive of {terr} vascular distribution.")
             
    else:
        findings_list.append("• No definite areas of restricted diffusion identified.")
        findings_list.append("• Brain parenchyma demonstrates normal signal intensity.")

    # Site of Infarct Checklist
    sites = [
        "Frontal Lobe", "Parietal", "Temporal", "Occipital",
        "Brain Stem", "Cerebellar", "Thalamic", "Basal Ganglia",
        "Int Capsule", "Ext Capsule", "Insular Cortex"
    ]
    
    # Mapping for robust matching (lowercase)
    site_keywords = {
        "Frontal Lobe": ["frontal"],
        "Parietal": ["parietal"],
        "Temporal": ["temporal"],
        "Occipital": ["occipital"],
        "Brain Stem": ["brain stem", "brainstem", "pons", "medulla", "midbrain"],
        "Cerebellar": ["cerebell"],
        "Thalamic": ["thalam"],
        "Basal Ganglia": ["basal ganglia", "caudate", "putamen", "globus pallidus", "lentiform"],
        "Int Capsule": ["internal capsule"],
        "Ext Capsule": ["external capsule"],
        "Insular Cortex": ["insula"]
    }
    
    checklist_lines = []
    # Normalize detected locations
    # "Left frontal lobe" -> "left frontal lobe"
    detected_text = " ".join([l.lower() for l in parsed_data.get("location", [])])
    
    max_len = 4
    rows = []
    current_row = []
    
    for site in sites:
        keywords = site_keywords.get(site, [site.lower()])
        is_checked = any(k in detected_text for k in keywords)

        marker = "[x]" if is_checked else "[ ]"
        current_row.append(f"{marker} {site}")
        
        if len(current_row) >= max_len:
            rows.append("  ".join(current_row))
            current_row = []
    
    if current_row:
        rows.append("  ".join(current_row))
        
    site_checklist = "\n".join(rows)

    findings_list.append("\nSITE OF INFARCT:")
    findings_list.append(site_checklist + "\n")

    findings_text = "\n".join(findings_list)

    # Construct Impression
    impression = ""
    if parsed_data["infarction_present"]:
        impression = f"Acute {parsed_data['laterality'].lower()} hemispheric infarction involving the {', '.join(parsed_data['location']).lower()}."
        if not adc_confirmed:
            impression += " (LIMITATION: ADC signals ambiguous; T2 shine-through possible)."
    else:
        impression = "No MRI evidence of acute ischemic stroke."

    # Disclaimer
    disclaimer = """
--------------------------------------------------------------------------------
AI DISCLAIMER: 
This report was generated by an AI system. 
It is a PRELIMINARY SCREENING tool only.
NOT FOR CLINICAL DIAGNOSIS. All findings must be verified by a radiologist.
--------------------------------------------------------------------------------
"""

    report = f"""
================================================================================
                    MRI BRAIN STROKE ANALYSIS PROTOCOL
================================================================================
CASE ID: {case_id}
SEQUENCES ANALYZED: Axial DWI, ADC, FLAIR

FINDINGS:
{findings_text}

IMPRESSION:
{impression}
{disclaimer}
"""
    return report
